"""task created_at

Revision ID: 03faf98c4f3e
Revises: 58d19b210bdf
Create Date: 2026-09-12 17:15:54.080540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03faf98c4f3e'
down_revision: Union[str, Sequence[str], None] = '58d19b210bdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=True))

    # Заполняем задним числом: у уже созданных заказов времени создания не было,
    # а восстановить его нечем — ставим момент миграции. Сортировка по id
    # при этом остаётся верной, так что порядок заказов не поедет.
    from datetime import datetime
    op.execute(
        sa.text("UPDATE tasks SET created_at = :ts WHERE created_at IS NULL")
        .bindparams(ts=datetime.utcnow().isoformat())
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
