"""withdrawal requests

Revision ID: 58d19b210bdf
Revises: 4634d648e920
Create Date: 2026-09-12 17:10:49.198202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d19b210bdf'
down_revision: Union[str, Sequence[str], None] = '4634d648e920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('requisites', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'paid', 'rejected', 'cancelled', name='withdrawalstatus'), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('deposit', 'escrow_hold', 'escrow_release', 'escrow_refund', 'purchase', 'withdraw_hold', 'withdraw_refund', name='transactiontype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('deposit', 'escrow_hold', 'escrow_release', 'escrow_refund', 'purchase', 'withdraw_hold', 'withdraw_refund', name='transactiontype'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=True)

    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_id'))

    op.drop_table('withdrawal_requests')
    # ### end Alembic commands ###
