"""user created_at

Revision ID: b2dc7263be2e
Revises: 03faf98c4f3e
Create Date: 2026-09-12 17:17:27.931374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dc7263be2e'
down_revision: Union[str, Sequence[str], None] = '03faf98c4f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.String(), nullable=True))

    # Задним числом: у существующих аккаунтов времени регистрации не было,
    # восстановить нечем — ставим момент миграции.
    from datetime import datetime
    op.execute(
        sa.text("UPDATE users SET created_at = :ts WHERE created_at IS NULL")
        .bindparams(ts=datetime.utcnow().isoformat())
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
